### ISSUE TITLE
[MOVED] Shared notes export / import icon, not using download icon (2.3-beta2)

### ISSUE THREAD

**Issue by pedrobmarin** [alangecker/bbb-etherpad-skin#2]
From https://github.com/bigbluebutton/bigbluebutton/issues/11974

```
Describe the bug
The export / import icon on shared notes, is not using the download icon.
It is using the old icon just as described on #7054

To Reproduce
Steps to reproduce the behavior:

    Click shared notes to open shared notes pane
    See the export / import icon (screenshot)

Expected behavior
The icon should be download icon, just as #7054

BBB version (optional):
2.3-beta2
```

Mentioned issue at https://github.com/bigbluebutton/bigbluebutton/issues/7054

cc @galupa @mrkeksi

**Comment by pedrobmarin** [comment]
Personally I would advise against change and just leave as Etherpad is. From the little experience I have, maintaining a font file this way is not so easy.

**Comment by mrkeksi** [comment]
we already have a download icon in BBB which should be used so that it looks uniform. it could simply be overwritten with css and maybe "!important". not a nice solution but if the icons of etherpad do not fit or are difficult to replace, this should be preferred.

**Comment by pedrobmarin** [comment]
Yeah, I did that and that's why I pointed out the caveat.
